version: '3.7'
volumes:
  keycloak_data:
    driver: local
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/
    ports:
      - '9091:9091'
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=9091"
